apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mongo-secrets
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: mongo-connection
      type: Opaque
      data:
        - objectName: MongoConnectionString
          key: connectionString
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: d521e6fd-e147-4eba-a089-203e3cad2bbb
    keyvaultName: todo-kv-dev
    objects: |
      array:
        - |
          objectName: MongoConnectionString
          objectType: secret
    tenantId: 33f41344-f538-4bc2-8974-ea61752ae066
