apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mongo-secrets
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: mongo-connection
      type: Opaque
      data:
        - objectName: MongoConnectionString
          key: connectionString
  parameters:
    usePodIdentity: "false" # or "true" if using pod MI
    useVMManagedIdentity: "true"
    userAssignedIdentityID: <client-id-of-managed-identity>
    keyvaultName: todo-kv-dev
    objects: |
      array:
        - |
          objectName: MongoConnectionString
          objectType: secret
    tenantId: <your-tenant-id>
