name: Infra + App Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  RESOURCE_GROUP: todo-rg-dev
  CLUSTER_NAME: todo-aks
  TERRAFORM_DIR: terraform
  K8S_MANIFEST_DIR: k8s-manifests
  PROJECT_NAME: todo
  ENVIRONMENT: dev
  GITHUB_REPO: xavrema/todo
  ACR_NAME: todoacr
  AKS_NAME: todoaks
  COSMOS_ACCOUNT_NAME: todocosmos
  COSMOS_DB_NAME: tododb
  MONGO_COLLECTION_NAME: todoitems

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Clear Azure CLI cache & tokens
        run: |
          az logout || true
          az account clear || true

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${ { secrets.AZURE_CLIENT_ID } }
          tenant-id: ${ { secrets.AZURE_TENANT_ID } }
          subscription-id: ${ { secrets.AZURE_SUBSCRIPTION_ID } }
    allow-no-subscriptions: true

          allow-no-subscriptions: true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          terraform plan \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var="resource_group_name=todo-rg" \
            -var="project_name=todo" \
            -var="environment=dev" \
            -var="github_repo=xavrema/todo_infra" \
            -var="acr_name=todoregistryxyz" \
            -var="aks_name=todo-aks" \
            -var="cosmos_account_name=todo-cosmosdb-dev" \
            -var="cosmos_db_name=todo-db" \
            -var="mongo_collection_name=users"

      - name: Terraform Apply
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          terraform apply -auto-approve \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var="resource_group_name=todo-rg" \
            -var="project_name=todo" \
            -var="environment=dev" \
            -var="github_repo=xavrema/todo_infra" \
            -var="acr_name=todoregistryxyz" \
            -var="aks_name=todo-aks" \
            -var="cosmos_account_name=todo-cosmosdb-dev" \
            -var="cosmos_db_name=todo-db" \
            -var="mongo_collection_name=users"

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --name ${{ env.CLUSTER_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --overwrite-existing

      - name: Deploy CSI SecretProviderClass
        run: kubectl apply -f ${{ env.K8S_MANIFEST_DIR }}/secretproviderclass.yaml

      - name: Deploy App
        run: kubectl apply -f ${{ env.K8S_MANIFEST_DIR }}/deployment-with-secret.yaml
